<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="user_test" tests="2" skipped="0" failures="2" errors="0" timestamp="2024-09-09T19:34:05" hostname="subhankar-modern14b5m" time="3.150583382"><testcase name="user_test::user_tests::contract_provider" classname="user_test" time="0.919851168"><failure message="assertion failed">thread &apos;user_test::user_tests::contract_provider&apos; panicked at tests/idtoken/mod.rs:12:9:
error   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: metadata

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</failure></testcase><testcase name="user_test::user_tests::contract_consumer" classname="user_test" time="3.150127948"><failure message="assertion failed">String(&quot;{\n                \&quot;id\&quot;: 1,\n                \&quot;user_name\&quot;: \&quot;biswas\&quot;,\n                \&quot;comment\&quot;: \&quot;user_test added \&quot;\n                }&quot;)
thread &apos;user_test::user_tests::contract_consumer&apos; panicked at tests/cloud_storage/mod.rs:12:60:
called `Result::unwrap()` on an `Err` value: CredentialsIOError(Os { code: 2, kind: NotFound, message: &quot;No such file or directory&quot; })
</failure></testcase>
</testsuite>